name: "Test Bump-up the version manually"

on:
  workflow_dispatch:
    inputs:
      flag:
        required: true
        type: string
        description: "Flag like dev, patch and release."

jobs:
  testbumpupversion:
    uses: ./.github/workflows/bump-version.yml
    with:
      flag: ${{ inputs.flag }}