name: "Test Bump-up verison"

on:
  pull_request:
    types: [opened, reopened]

jobs:
  addlabels:
    name: Test bump-up
    runs-on: ubuntu-latest
    steps:
      - name: Test bump-up
        uses: ./.github/workflows/bump-version.yml@bumpversion
          with:
            flag: patch