name: Verify pull requests

on:
  pull_request:
    types: [labeled, unlabeled]

env:
  LABELS: ${{ join( github.event.pull_request.labels.*.name, ' ' ) }}

jobs:
  verifylabels:
    name: verify_labels
    runs-on: ubuntu-latest
    steps:
      - name: Verify pull request has required labels
        run: |
          for label in ${{ env.LABELS }}; do
            if [ $label == "no-release" ] || [ $label == "development-release" ] || [ $label == "production-release" ]
            then
              exit 0
            fi
          done
          echo "Pull request must have one of no-release, production-release or development-release label."
          exit 1

      - name: Verify pull request has correct labels
        run: |
          for label in ${{ env.LABELS }}; do
            if ([ $label == "no-release" ] && [ $label == "development-release" ]) || ([ $label == "no-release" ] && [ $label == "production-release" ]) || ([ $label == "production-release" ] && [ $label == "development-release" ])
            then
              echo "Pull request can only have one of no-release, production-release or development-release label."
              exit 1
            fi
          done

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v22
        with:
          since_last_remote_commit: 'true'

      - name: Verify development-release label
        if: contains (env.LABELS, 'development-release')
        run: |
          if [ github.base_ref != 'develop' ]
          then
            echo "Pull request with development-release label must have base reference branch as develop."
            exit 1
          fi
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
              if [ $file == *"VERSION"* ] || [ $file == *".bumpversion.cfg"* ]
              then
                  echo "Pull request with development-release label must not have VERSION updates to python Packages."
                  exit 1
              fi
          done

      - name: Verify production-release label
        if: contains (env.LABELS, 'production-release')
        run: |
          if [ github.base_ref != 'master' ] || [ github.base_ref != 'develop' ]
          then
            echo "Pull request with production-release label must have base reference branch as master or develop."
            exit 1
          fi
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
              if [ $file != *"VERSION"* ] || [ $file != *".bumpversion.cfg"* ]
              then
                  echo "Pull request with production-release label must only have VERSION updates to python Packages."
                  exit 1
              fi
          done
